#!/bin/sh
echo "Content-Type: application/json"
echo ""
apcli=`ifconfig | grep apcli0`
while [[ -z "$apcli" ]]
do
    apcli=`ifconfig | grep apcli0`
done

ip=`ifconfig apcli0 | grep 'inet addr:'| cut -d: -f2 | awk '{ print $1}'`
if [ $ip ]; then
    echo "{\"result\":\"success\",\"message\":\"connected with IP $ip\", \"ip\":\"$ip\"}"
else
    echo "{\"result\":\"error\",\"message\":\"can not connect to $ussid\"}"
fi