#!/bin/sh

ussid=$1
upass=$2
iwpriv ra0 set SiteSurvey=0
sleep 2
OUTPUT=`iwpriv ra0 get_site_survey | grep '^[0-9]'`
while read line
do
	ssid=`echo $line | awk '{print $2}'`
	echo $line
	if [ "$ssid"x = "$ussid"x ]; then
# 	# Set interfaces file
		umode=""
		uencryp=""

		channel=`echo $line | awk '{print $1}'`
		security=`echo $line | awk '{print $5}'`
		mac=`echo $line | awk '{print $4}'`

		if [ "$security"x = "WPA1PSKWPA2PSK/TKIPAES"x ]; then
			umode="WPA2PSK"
        		uencryp="AES"
		elif [ "$security"x = "WPA1PSKWPA2PSK/AES"x ]; then
			umode="WPA2PSK"
        		uencryp="AES"
		elif [ "$security"x = "WPA2PSK/AES"x ]; then
        		umode="WPA2PSK"
        		uencryp="AES"
  	  	elif [ "$security"x = "WPA2PSK/TKIP"x ]; then
        		umode="WPA2PSK"
	        	uencryp="TKIP"
   		elif [ "$security"x = "WPAPSK/TKIPAES"x ]; then
        		umode="WPAPSK"
	        	uencryp="TKIP"
		elif [ "$security"x = "WPAPSK/AES"x ]; then
   			umode="WPAPSK"
        	uencryp="AES"
		elif [ "$security"x = "WPAPSK/TKIP"x ]; then
    		umode="WPAPSK"
        	uencryp="TKIP"
		elif [ "$security"x = "WEP"x ]; then
    		umode="WEP"
        	uencryp="WEP"
   		fi

		echo $umode
		echo $uencryp
		echo $channel
#		nvram_set 2860  ApCliSsid $ussid
#		nvram_set 2860  ApCliBssid  $mac
#		nvram_set 2860  ApCliAuthMode $umode
#		nvram_set 2860  ApCliEncrypType $uencryp
#		nvram_set 2860  ApCliWPAPSK $upass
#		nvram_set 2860  Channel $chanel
		echo "start uci set ..."
		uci set wireless.@wifi-iface[0].ApCliSsid=$ussid
#		uci set wireless.@wifi-iface[0].ApCliBssid=$mac
		uci set wireless.@wifi-iface[0].ApCliEnable=1
		uci set wireless.@wifi-iface[0].ApCliAuthMode=$umode
		uci set wireless.@wifi-iface[0].ApCliEncrypType=$uencryp
		uci set wireless.@wifi-iface[0].ApCliWPAPSK=$upass
		uci set wireless.mt7628.channel=$channel
		uci set network.wan=interface
		uci set network.wan.ifname=apcli0
		uci set network.wan.proto=dhcp
		uci set	network.lan.ipaddr=192.168.99.1
		uci commit
		/etc/init.d/network restart
        exit 0
	fi
done <<EOF
$OUTPUT
EOF
